Update rdp-tailscale-rustdesk-A.yml

diff --git a/.github/workflows/rdp-tailscale-rustdesk-A.yml b/.github/workflows/rdp-tailscale-rustdesk-A.yml
--- a/.github/workflows/rdp-tailscale-rustdesk-A.yml
+++ b/.github/workflows/rdp-tailscale-rustdesk-A.yml
@@ -107,22 +107,45 @@ jobs:
 
           Write-Host "========== EXTRACTION COMPLETE =========="
 
-      - name: Find AfterFX
-        run: |
-          $ae = Get-ChildItem "C:\AE2025" -Recurse -Filter "AfterFX.exe" | Select-Object -First 1
+      - name: Run Adobe Installer
+  run: |
+    $setup = Get-ChildItem "C:\AE2025" -Recurse -Filter "Set-up.exe" | Select-Object -First 1
 
-          if ($ae) {
-            echo "AE_PATH=$($ae.FullName)" >> $env:GITHUB_ENV
-            Write-Host "FOUND: $($ae.FullName)"
-          }
-          else {
-            Write-Error "AfterFX.exe not found"
-            exit 1
-          }
+    if ($setup) {
 
-      - name: Launch AE
-        run: |
-          Start-Process "$env:AE_PATH"
+      Write-Host "FOUND INSTALLER:"
+      Write-Host $setup.FullName
+
+      Start-Process `
+      -FilePath $setup.FullName `
+      -ArgumentList "--silent" `
+      -Wait
+
+      Write-Host "INSTALL COMPLETE"
+    }
+    else {
+      Write-Error "Set-up.exe not found"
+      exit 1
+    }
+
+- name: Find AfterFX
+  run: |
+    $ae = Get-ChildItem "C:\Program Files" -Recurse -Filter "AfterFX.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
+
+    if ($ae) {
+      echo "AE_PATH=$($ae.FullName)" >> $env:GITHUB_ENV
+
+      Write-Host "FOUND AFTERFX:"
+      Write-Host $ae.FullName
+    }
+    else {
+      Write-Error "AfterFX.exe not found"
+      exit 1
+    }
+
+- name: Launch AE
+  run: |
+    Start-Process "$env:AE_PATH"
 
       - name: Show RDP Info
         run: |
